[package]
authors = ["Sam Rijs <srijs@airpost.net>"]
name = "cfn_generator"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
flate2 = "1.0"
heck = "0.3"
itertools = "0.10"
reqwest = {version = "0.11", features = ["blocking", "json"]}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
